services:
  mongodb:
    build:
      context: ./ex1/dataset
      dockerfile: Dockerfile
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=jogostabuleiro
    volumes:
      - mongodb:/data/db
    networks:
      - engweb

  # ex1 - API de dados sobre Jogos de Tabuleiro
  data-api:
    build:
      context: ./ex1
      dockerfile: Dockerfile
    container_name: data-api
    environment:
      - MONGO_URL=mongodb://mongodb:27017/jogostabuleiro
      - DB_NAME=jogostabuleiro
      - PORT=17000
    ports:
      - "17000:17000"
    depends_on:
      - mongodb
    networks:
      - engweb

  # ex2 - API "A Minha Lista de Leituras"
  api-livros:
    build:
      context: ./ex2/api
      dockerfile: Dockerfile
    container_name: api-livros
    environment:
      - MONGO_URL=mongodb://mongodb:27017/biblioteca
      - DB_NAME=biblioteca
      - PORT=19020
    ports:
      - "19020:19020"
    depends_on:
      - mongodb
    networks:
      - engweb

  # ex2 - Nginx a servir o index.html
  web-livros:
    build:
      context: ./ex2/web
      dockerfile: Dockerfile
    container_name: web-livros
    ports:
      - "19021:80"
    depends_on:
      - api-livros
    networks:
      - engweb

networks:
  engweb:
    driver: bridge

volumes:
  mongodb:
